## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Medievalists Design Games"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = true
#canonifyURLs = true

# Local
baseURL = "/"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/Rook–Builder Arrangement.png"
  favicon = true
  location = "University of Chicago"

[Params.social]
  # twitter = "https://twitter.com/caressofsteel_"
  # email = "caressofsteel@protonmail.com"
  # instagram = "https://instagram.com"
  # telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
