## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = true
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"
