## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = true

# Remote
baseURL = 'https://medievalistsdesign.games/'
publishDir = "public"
